Linux 3.4 compat: __clear_close_on_exec replaces FD_CLR
torvalds/linux@1dce27c5aa6770e9d195f2bb7db1db3d4dde5591 introduced
__clear_close_on_exec() as a replacement for FD_CLR. Further commits
appear to have removed FD_CLR from the Linux source tree. This causes
the following failure:

error: implicit declaration of function '__FD_CLR'
[-Werror=implicit-function-declaration]

To correct this, we introduce an autotools check for
__clear_close_on_exec() and use it whenever it is available.

Signed-off-by: Richard Yao <ryao@gentoo.org>